# Generated by Django 5.2.12 on 2026-04-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
        ('sales', '0004_sale_sales_sale_complet_f623d7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_normalized'], name='debt_custom_phone_n_e0b218_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status', 'created_at'], name='debt_debt_status_66a61b_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['customer', 'status', 'due_date'], name='debt_debt_custome_b2234b_idx'),
        ),
    ]
