# Generated by Django 5.2.12 on 2026-04-23 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='Geeks POS', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('footer_note', models.CharField(blank=True, default='Rahmat!', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('encoding', models.CharField(default='cp866', max_length=32)),
                ('transliterate_uz', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
