# Generated by Django 5.2.12 on 2026-04-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_hardware_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='label_printer_type',
            field=models.CharField(choices=[('ESC_POS', 'ESC/POS'), ('TSPL', 'TSPL')], default='TSPL', max_length=16),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='receipt_printer_type',
            field=models.CharField(choices=[('ESC_POS', 'ESC/POS'), ('TSPL', 'TSPL')], default='ESC_POS', max_length=16),
        ),
    ]
