# Generated by Django 5.2.12 on 2026-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_lock_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='label_printer_port',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='receipt_lang',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='receipt_printer_port',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
