# Generated by Django 5.2.12 on 2026-04-27 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_public_sale_no_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['completed_at'], name='sales_sale_complet_f623d7_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-completed_at'], name='sales_sale_status_4bd04f_idx'),
        ),
    ]
